resources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/eddytnk/deploy-springboot-app-using-concourse-ci
    branch: master

- name: s3-stored-jar
  type: s3
  source:
    bucket: eddytnk
    region_name: us-east-2
    regexp: jars/springboot-concourse-(.*)-SNAPSHOT.jar
    access_key_id: ((AWSAccessKeyId))
    secret_access_key: ((AWSSecretKey))

- name: pcf-resource
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((PCF_EMAIL))
    password: ((PCF_PASSWORD))
    organization: ((PCF_ORG))
    space: ((PCF_SPACE))
    skip_cert_check: false

jobs:
- name: test-and-build
  public: true
  plan:
    - get: source-code-from-github
      trigger: true
    - get: s3-stored-jar
    - task: run-test-and-build-jar-file
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: source-code-from-github
        outputs:
        - name: jar-file
        caches:
        - path: source-code-from-github/.m2
        run:
          path: ./source-code-from-github/ci/test-and-build.sh
    - put: s3-stored-jar
      params:
        file: jar-file/*.jar

- name: deploy-app-to-pcf
  public: true
  plan:
  - get: s3-stored-jar
    passed: [test-and-build]
    trigger: true
  - get: source-code-from-github
    #- task: create-some-files
    #  config:
     #   inputs:
      #  - name: s3-stored-jar
       # outputs:
        #- name: jar-from-s3
  - put: pcf-resource
    params:
      manifest: source-code-from-github/ci/manifest.yml


